# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/OhmoriG_Rogue/Downloads/fpga-advanced-2024/project_1-verilog-exe1/project_1-verilog-exe1.srcs/sources_1/ip/dsp_macro_1/dsp_macro_1.xci
# IP: The module: 'dsp_macro_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OhmoriG_Rogue/Downloads/fpga-advanced-2024/project_1-verilog-exe1/project_1-verilog-exe1.gen/sources_1/ip/dsp_macro_1/dsp_macro_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_macro_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/OhmoriG_Rogue/Downloads/fpga-advanced-2024/project_1-verilog-exe1/project_1-verilog-exe1.srcs/sources_1/ip/dsp_macro_1/dsp_macro_1.xci
# IP: The module: 'dsp_macro_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OhmoriG_Rogue/Downloads/fpga-advanced-2024/project_1-verilog-exe1/project_1-verilog-exe1.gen/sources_1/ip/dsp_macro_1/dsp_macro_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_macro_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
